title      : scott.cgi
lang       : zh
description: 编程写作 / 迭代认知 / 执行计划
copyright  : © 2018 - 2021 Novak Ho All Rights Reserved

nav:
 - name: 中文
   link: /
 - name: En
   link: /novak.gitlab.io/about/
